/**************************************************************/
/* Automatically generated by './mkconfig.sh'.  Do note edit! */
/**************************************************************/
#define YALS_OS "Linux vvv-dejavu 4.19.12-arch1-1-ARCH x86_64"
#define YALS_COMPILED "Mon 11 Mar 20:16:09 CET 2019"
#define YALS_RELEASED "Fr 1. Mär 05:17:48 CET 2019"
#define YALS_VERSION "03v"
#define YALS_ID "b1316746d40f72f147cde3f4ec54fadbe0730427"
